import os

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
KAFKA_AIRFLOW_V2_DAG_RUN_TOPIC_NAME = os.getenv("KAFKA_AIRFLOW_V2_DAG_RUN_TOPIC_NAME", "AIRFLOW_V2_DAG_RUN_LOGS")
KAFKA_AIRFLOW_V2_TASK_INSTANCE_TOPIC_NAME = os.getenv("KAFKA_AIRFLOW_V2_TASK_INSTANCE_TOPIC_NAME", "AIRFLOW_V2_TASK_INSTANCE_LOGS")
KAFKA_AIRFLOW_V3_DAG_RUN_TOPIC_NAME = os.getenv("KAFKA_AIRFLOW_V3_DAG_RUN_TOPIC_NAME", "AIRFLOW_V3_DAG_RUN_LOGS")
KAFKA_AIRFLOW_V3_TASK_INSTANCE_TOPIC_NAME = os.getenv("KAFKA_AIRFLOW_V3_TASK_INSTANCE_TOPIC_NAME", "AIRFLOW_V3_TASK_INSTANCE_LOGS")
KAFKA_MSK_ARN = os.getenv("KAFKA_MSK_ARN", None)
KAFKA_MSK_AWS_REGION = KAFKA_MSK_ARN.split(":")[3] if KAFKA_MSK_ARN is not None else None
SCHEMA_REGISTRY_URL = os.getenv("SCHEMA_REGISTRY_URL", None)
LOGGING_LEVEL = os.getenv("LOGGING_LEVEL", "INFO").upper()
ENVIRONMENT = os.getenv("ENVIRONMENT", "DEV").upper()
